language: node_js
node_js: "12"
os:
- linux
- osx
dist: focal
osx_image: xcode8.3
sudo: required

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - wine
    - mono-devel

# before-install:
#   - sudo apt-get update
#   - sudo apt-get install rpm

install:
# - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget http://archive.ubuntu.com/ubuntu/pool/universe/r/rpm/rpm_4.16.1.2+dfsg1-0.3_amd64.deb; fi
# - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo dpkg -i rpm_4.16.1.2+dfsg1-0.3_amd64.deb || sudo apt-get install -f; fi
- npm install

script:
- npm run make

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: out/make/**/*
  skip_cleanup: true
  draft: true