language: node_js
node_js: "12"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: required

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    # - rpm
    - wine
    - mono-devel

before-install:
  - sudo apt-get update
  - sudo apt-get install rpm

install:
- npm install

script:
- npm run make

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: out/make/**/*
  skip_cleanup: true
  draft: true