language: node_js
node_js: "6"
os:
- linux
- osx
dist: trusty
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - wine
    - mono-devel

install:
- npm install

script:
- npm run make